"""Add student face enrollment table

Revision ID: 5f2d0ace900c
Revises: cd2db3ad4328
Create Date: 2026-09-27 10:36:43.261180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2d0ace900c'
down_revision: Union[str, Sequence[str], None] = 'cd2db3ad4328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_faces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('is_enrolled', sa.Boolean(), nullable=False),
    sa.Column('consent_recorded', sa.Boolean(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_faces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_faces_student_id'), ['student_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_faces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_faces_student_id'))

    op.drop_table('student_faces')
    # ### end Alembic commands ###
