"""create teacher assignments table

Revision ID: 9b10a1bf2280
Revises: 35761e3326df
Create Date: 2026-09-25 21:45:23.408232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b10a1bf2280'
down_revision: Union[str, Sequence[str], None] = '35761e3326df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('academic_class_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['academic_class_id'], ['academic_classes.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'academic_class_id', name='uq_teacher_class_assignment')
    )
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teacher_assignments_academic_class_id'), ['academic_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teacher_assignments_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_teacher_assignments_academic_class_id'))

    op.drop_table('teacher_assignments')
    # ### end Alembic commands ###
