"""create attendance corrections audit table

Revision ID: cd2db3ad4328
Revises: 32784277d208
Create Date: 2026-09-26 13:29:38.794333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2db3ad4328'
down_revision: Union[str, Sequence[str], None] = '32784277d208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_record_id', sa.Integer(), nullable=False),
    sa.Column('corrected_by', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('corrected_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("new_status IN ('PRESENT', 'ABSENT', 'OD', 'LATE')", name='ck_correction_new_status'),
    sa.CheckConstraint("old_status IN ('PRESENT', 'ABSENT', 'OD', 'LATE')", name='ck_correction_old_status'),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ),
    sa.ForeignKeyConstraint(['corrected_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_corrections_attendance_record_id'), ['attendance_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_corrections_corrected_by'), ['corrected_by'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_corrections_corrected_by'))
        batch_op.drop_index(batch_op.f('ix_attendance_corrections_attendance_record_id'))

    op.drop_table('attendance_corrections')
    # ### end Alembic commands ###
