"""Add departments and academic classes

Revision ID: f34ba05b6fe0
Revises: 16480cca6b8c
Create Date: 2026-09-25 17:12:51.311916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34ba05b6fe0'
down_revision: Union[str, Sequence[str], None] = '16480cca6b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)

    op.create_table('academic_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'name', 'section', 'semester', name='uq_academic_class')
    )
    with op.batch_alter_table('academic_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_classes_department_id'), ['department_id'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_class_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_academic_class_id'), ['academic_class_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_students_academic_class_id',
            'academic_classes',
            ['academic_class_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(
            'fk_students_academic_class_id',
            type_='foreignkey'
        )
        batch_op.drop_index(batch_op.f('ix_students_academic_class_id'))
        batch_op.drop_column('academic_class_id')

    with op.batch_alter_table('academic_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_classes_department_id'))

    op.drop_table('academic_classes')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    # ### end Alembic commands ###
